const data = [ { id: '0id',
    title: 'item0',
    rating: 3,
    cost: 25,
    duration: 15,
    open: 29,
    close: 89,
    note: 'some string' },
  { id: '1id',
    title: 'item1',
    rating: 5,
    cost: 183,
    duration: 3,
    open: 44,
    close: 127,
    note: 'some string' },
  { id: '2id',
    title: 'item2',
    rating: 3,
    cost: 147,
    duration: 1,
    open: 10,
    close: 105,
    note: 'some string' },
  { id: '3id',
    title: 'item3',
    rating: 4,
    cost: 137,
    duration: 13,
    open: 41,
    close: 116,
    note: 'some string' },
  { id: '4id',
    title: 'item4',
    rating: 3,
    cost: 144,
    duration: 9,
    open: 36,
    close: 100,
    note: 'some string' },
  { id: '5id',
    title: 'item5',
    rating: 5,
    cost: 155,
    duration: 7,
    open: 4,
    close: 69,
    note: 'some string' },
  { id: '6id',
    title: 'item6',
    rating: 4,
    cost: 139,
    duration: 14,
    open: 47,
    close: 112,
    note: 'some string' },
  { id: '7id',
    title: 'item7',
    rating: 1,
    cost: 93,
    duration: 11,
    open: 27,
    close: 104,
    note: 'some string' },
  { id: '8id',
    title: 'item8',
    rating: 1,
    cost: 173,
    duration: 11,
    open: 14,
    close: 73,
    note: 'some string' },
  { id: '9id',
    title: 'item9',
    rating: 2,
    cost: 128,
    duration: 8,
    open: 2,
    close: 91,
    note: 'some string' },
  { id: '10id',
    title: 'item10',
    rating: 4,
    cost: 169,
    duration: 6,
    open: 11,
    close: 133,
    note: 'some string' },
  { id: '11id',
    title: 'item11',
    rating: 3,
    cost: 152,
    duration: 1,
    open: 19,
    close: 100,
    note: 'some string' },
  { id: '12id',
    title: 'item12',
    rating: 3,
    cost: 181,
    duration: 4,
    open: 30,
    close: 67,
    note: 'some string' },
  { id: '13id',
    title: 'item13',
    rating: 2,
    cost: 187,
    duration: 9,
    open: 22,
    close: 132,
    note: 'some string' },
  { id: '14id',
    title: 'item14',
    rating: 3,
    cost: 25,
    duration: 9,
    open: 34,
    close: 85,
    note: 'some string' },
  { id: '15id',
    title: 'item15',
    rating: 4,
    cost: 182,
    duration: 2,
    open: 42,
    close: 48,
    note: 'some string' },
  { id: '16id',
    title: 'item16',
    rating: 1,
    cost: 182,
    duration: 4,
    open: 3,
    close: 75,
    note: 'some string' },
  { id: '17id',
    title: 'item17',
    rating: 1,
    cost: 24,
    duration: 14,
    open: 45,
    close: 55,
    note: 'some string' },
  { id: '18id',
    title: 'item18',
    rating: 2,
    cost: 64,
    duration: 4,
    open: 41,
    close: 123,
    note: 'some string' },
  { id: '19id',
    title: 'item19',
    rating: 5,
    cost: 117,
    duration: 14,
    open: 45,
    close: 102,
    note: 'some string' },
  { id: '20id',
    title: 'item20',
    rating: 5,
    cost: 178,
    duration: 12,
    open: 17,
    close: 107,
    note: 'some string' },
  { id: '21id',
    title: 'item21',
    rating: 5,
    cost: 81,
    duration: 14,
    open: 25,
    close: 73,
    note: 'some string' },
  { id: '22id',
    title: 'item22',
    rating: 3,
    cost: 124,
    duration: 7,
    open: 39,
    close: 94,
    note: 'some string' },
  { id: '23id',
    title: 'item23',
    rating: 3,
    cost: 25,
    duration: 15,
    open: 29,
    close: 61,
    note: 'some string' },
  { id: '24id',
    title: 'item24',
    rating: 4,
    cost: 167,
    duration: 11,
    open: 8,
    close: 128,
    note: 'some string' },
  { id: '25id',
    title: 'item25',
    rating: 1,
    cost: 140,
    duration: 2,
    open: 24,
    close: 62,
    note: 'some string' },
  { id: '26id',
    title: 'item26',
    rating: 2,
    cost: 171,
    duration: 12,
    open: 6,
    close: 122,
    note: 'some string' },
  { id: '27id',
    title: 'item27',
    rating: 2,
    cost: 184,
    duration: 3,
    open: 18,
    close: 86,
    note: 'some string' },
  { id: '28id',
    title: 'item28',
    rating: 4,
    cost: 167,
    duration: 14,
    open: 15,
    close: 53,
    note: 'some string' },
  { id: '29id',
    title: 'item29',
    rating: 5,
    cost: 73,
    duration: 10,
    open: 21,
    close: 78,
    note: 'some string' },
  { id: '30id',
    title: 'item30',
    rating: 1,
    cost: 192,
    duration: 15,
    open: 0,
    close: 143,
    note: 'some string' },
  { id: '31id',
    title: 'item31',
    rating: 2,
    cost: 140,
    duration: 7,
    open: 35,
    close: 94,
    note: 'some string' },
  { id: '32id',
    title: 'item32',
    rating: 4,
    cost: 13,
    duration: 11,
    open: 36,
    close: 121,
    note: 'some string' },
  { id: '33id',
    title: 'item33',
    rating: 1,
    cost: 177,
    duration: 3,
    open: 34,
    close: 130,
    note: 'some string' },
  { id: '34id',
    title: 'item34',
    rating: 4,
    cost: 186,
    duration: 8,
    open: 0,
    close: 130,
    note: 'some string' },
  { id: '35id',
    title: 'item35',
    rating: 4,
    cost: 79,
    duration: 12,
    open: 13,
    close: 103,
    note: 'some string' },
  { id: '36id',
    title: 'item36',
    rating: 1,
    cost: 150,
    duration: 3,
    open: 25,
    close: 74,
    note: 'some string' },
  { id: '37id',
    title: 'item37',
    rating: 4,
    cost: 6,
    duration: 15,
    open: 35,
    close: 140,
    note: 'some string' },
  { id: '38id',
    title: 'item38',
    rating: 1,
    cost: 140,
    duration: 14,
    open: 3,
    close: 71,
    note: 'some string' },
  { id: '39id',
    title: 'item39',
    rating: 1,
    cost: 164,
    duration: 12,
    open: 22,
    close: 92,
    note: 'some string' },
  { id: '40id',
    title: 'item40',
    rating: 1,
    cost: 107,
    duration: 3,
    open: 41,
    close: 66,
    note: 'some string' },
  { id: '41id',
    title: 'item41',
    rating: 5,
    cost: 130,
    duration: 8,
    open: 42,
    close: 62,
    note: 'some string' },
  { id: '42id',
    title: 'item42',
    rating: 1,
    cost: 59,
    duration: 8,
    open: 17,
    close: 102,
    note: 'some string' },
  { id: '43id',
    title: 'item43',
    rating: 1,
    cost: 17,
    duration: 7,
    open: 46,
    close: 98,
    note: 'some string' },
  { id: '44id',
    title: 'item44',
    rating: 2,
    cost: 140,
    duration: 12,
    open: 14,
    close: 123,
    note: 'some string' },
  { id: '45id',
    title: 'item45',
    rating: 2,
    cost: 155,
    duration: 11,
    open: 18,
    close: 106,
    note: 'some string' },
  { id: '46id',
    title: 'item46',
    rating: 1,
    cost: 123,
    duration: 8,
    open: 25,
    close: 112,
    note: 'some string' },
  { id: '47id',
    title: 'item47',
    rating: 5,
    cost: 167,
    duration: 15,
    open: 46,
    close: 80,
    note: 'some string' },
  { id: '48id',
    title: 'item48',
    rating: 1,
    cost: 122,
    duration: 14,
    open: 42,
    close: 70,
    note: 'some string' },
  { id: '49id',
    title: 'item49',
    rating: 5,
    cost: 199,
    duration: 4,
    open: 43,
    close: 56,
    note: 'some string' },
  { id: '50id',
    title: 'item50',
    rating: 4,
    cost: 150,
    duration: 1,
    open: 3,
    close: 125,
    note: 'some string' },
  { id: '51id',
    title: 'item51',
    rating: 3,
    cost: 122,
    duration: 11,
    open: 27,
    close: 79,
    note: 'some string' },
  { id: '52id',
    title: 'item52',
    rating: 2,
    cost: 53,
    duration: 4,
    open: 27,
    close: 114,
    note: 'some string' },
  { id: '53id',
    title: 'item53',
    rating: 5,
    cost: 144,
    duration: 6,
    open: 34,
    close: 93,
    note: 'some string' },
  { id: '54id',
    title: 'item54',
    rating: 2,
    cost: 59,
    duration: 6,
    open: 6,
    close: 98,
    note: 'some string' },
  { id: '55id',
    title: 'item55',
    rating: 2,
    cost: 34,
    duration: 4,
    open: 29,
    close: 55,
    note: 'some string' },
  { id: '56id',
    title: 'item56',
    rating: 3,
    cost: 174,
    duration: 4,
    open: 4,
    close: 84,
    note: 'some string' },
  { id: '57id',
    title: 'item57',
    rating: 4,
    cost: 116,
    duration: 9,
    open: 38,
    close: 126,
    note: 'some string' },
  { id: '58id',
    title: 'item58',
    rating: 2,
    cost: 200,
    duration: 10,
    open: 24,
    close: 92,
    note: 'some string' },
  { id: '59id',
    title: 'item59',
    rating: 1,
    cost: 101,
    duration: 11,
    open: 37,
    close: 114,
    note: 'some string' },
  { id: '60id',
    title: 'item60',
    rating: 2,
    cost: 13,
    duration: 4,
    open: 27,
    close: 105,
    note: 'some string' },
  { id: '61id',
    title: 'item61',
    rating: 5,
    cost: 123,
    duration: 8,
    open: 26,
    close: 110,
    note: 'some string' },
  { id: '62id',
    title: 'item62',
    rating: 5,
    cost: 9,
    duration: 7,
    open: 29,
    close: 139,
    note: 'some string' },
  { id: '63id',
    title: 'item63',
    rating: 4,
    cost: 12,
    duration: 8,
    open: 3,
    close: 139,
    note: 'some string' },
  { id: '64id',
    title: 'item64',
    rating: 1,
    cost: 196,
    duration: 8,
    open: 33,
    close: 132,
    note: 'some string' },
  { id: '65id',
    title: 'item65',
    rating: 5,
    cost: 144,
    duration: 14,
    open: 1,
    close: 85,
    note: 'some string' },
  { id: '66id',
    title: 'item66',
    rating: 2,
    cost: 10,
    duration: 16,
    open: 43,
    close: 72,
    note: 'some string' },
  { id: '67id',
    title: 'item67',
    rating: 1,
    cost: 140,
    duration: 12,
    open: 25,
    close: 142,
    note: 'some string' },
  { id: '68id',
    title: 'item68',
    rating: 2,
    cost: 8,
    duration: 9,
    open: 12,
    close: 69,
    note: 'some string' },
  { id: '69id',
    title: 'item69',
    rating: 4,
    cost: 193,
    duration: 2,
    open: 43,
    close: 49,
    note: 'some string' },
  { id: '70id',
    title: 'item70',
    rating: 4,
    cost: 199,
    duration: 12,
    open: 8,
    close: 83,
    note: 'some string' },
  { id: '71id',
    title: 'item71',
    rating: 2,
    cost: 183,
    duration: 7,
    open: 14,
    close: 137,
    note: 'some string' },
  { id: '72id',
    title: 'item72',
    rating: 4,
    cost: 119,
    duration: 12,
    open: 39,
    close: 69,
    note: 'some string' },
  { id: '73id',
    title: 'item73',
    rating: 5,
    cost: 107,
    duration: 7,
    open: 34,
    close: 103,
    note: 'some string' },
  { id: '74id',
    title: 'item74',
    rating: 5,
    cost: 83,
    duration: 2,
    open: 17,
    close: 140,
    note: 'some string' },
  { id: '75id',
    title: 'item75',
    rating: 5,
    cost: 98,
    duration: 1,
    open: 15,
    close: 141,
    note: 'some string' },
  { id: '76id',
    title: 'item76',
    rating: 1,
    cost: 111,
    duration: 1,
    open: 32,
    close: 55,
    note: 'some string' },
  { id: '77id',
    title: 'item77',
    rating: 1,
    cost: 29,
    duration: 2,
    open: 14,
    close: 54,
    note: 'some string' },
  { id: '78id',
    title: 'item78',
    rating: 2,
    cost: 129,
    duration: 6,
    open: 9,
    close: 69,
    note: 'some string' },
  { id: '79id',
    title: 'item79',
    rating: 4,
    cost: 61,
    duration: 16,
    open: 33,
    close: 83,
    note: 'some string' },
  { id: '80id',
    title: 'item80',
    rating: 3,
    cost: 22,
    duration: 12,
    open: 18,
    close: 121,
    note: 'some string' },
  { id: '81id',
    title: 'item81',
    rating: 4,
    cost: 60,
    duration: 1,
    open: 34,
    close: 59,
    note: 'some string' },
  { id: '82id',
    title: 'item82',
    rating: 1,
    cost: 159,
    duration: 4,
    open: 45,
    close: 133,
    note: 'some string' },
  { id: '83id',
    title: 'item83',
    rating: 2,
    cost: 195,
    duration: 5,
    open: 28,
    close: 85,
    note: 'some string' },
  { id: '84id',
    title: 'item84',
    rating: 5,
    cost: 85,
    duration: 8,
    open: 7,
    close: 80,
    note: 'some string' },
  { id: '85id',
    title: 'item85',
    rating: 5,
    cost: 54,
    duration: 4,
    open: 15,
    close: 55,
    note: 'some string' },
  { id: '86id',
    title: 'item86',
    rating: 5,
    cost: 151,
    duration: 6,
    open: 32,
    close: 88,
    note: 'some string' },
  { id: '87id',
    title: 'item87',
    rating: 4,
    cost: 187,
    duration: 3,
    open: 31,
    close: 103,
    note: 'some string' },
  { id: '88id',
    title: 'item88',
    rating: 1,
    cost: 175,
    duration: 3,
    open: 40,
    close: 90,
    note: 'some string' },
  { id: '89id',
    title: 'item89',
    rating: 5,
    cost: 49,
    duration: 10,
    open: 10,
    close: 91,
    note: 'some string' },
  { id: '90id',
    title: 'item90',
    rating: 1,
    cost: 21,
    duration: 4,
    open: 8,
    close: 74,
    note: 'some string' },
  { id: '91id',
    title: 'item91',
    rating: 1,
    cost: 100,
    duration: 14,
    open: 12,
    close: 114,
    note: 'some string' },
  { id: '92id',
    title: 'item92',
    rating: 5,
    cost: 130,
    duration: 13,
    open: 44,
    close: 98,
    note: 'some string' },
  { id: '93id',
    title: 'item93',
    rating: 1,
    cost: 149,
    duration: 8,
    open: 31,
    close: 104,
    note: 'some string' },
  { id: '94id',
    title: 'item94',
    rating: 2,
    cost: 157,
    duration: 8,
    open: 40,
    close: 123,
    note: 'some string' },
  { id: '95id',
    title: 'item95',
    rating: 4,
    cost: 89,
    duration: 14,
    open: 3,
    close: 106,
    note: 'some string' },
  { id: '96id',
    title: 'item96',
    rating: 5,
    cost: 125,
    duration: 8,
    open: 38,
    close: 103,
    note: 'some string' },
  { id: '97id',
    title: 'item97',
    rating: 1,
    cost: 199,
    duration: 12,
    open: 34,
    close: 110,
    note: 'some string' },
  { id: '98id',
    title: 'item98',
    rating: 1,
    cost: 142,
    duration: 7,
    open: 39,
    close: 132,
    note: 'some string' },
  { id: '99id',
    title: 'item99',
    rating: 5,
    cost: 71,
    duration: 14,
    open: 40,
    close: 56,
    note: 'some string' } ]

export default data;
